# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Continuous Integration
on:
  pull_request:
    branches: [main]

jobs:
  Quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install Python Poetry
        uses: abatilo/actions-poetry@v2.1.0
        with:
          poetry-version: 1.8.3
      - name: Configure poetry
        shell: bash
        run: poetry config virtualenvs.in-project true
      - name: View poetry version
        run: poetry --version
      - name: Install dependencies
        run: |
          poetry install
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: >
            ${{ format('pre-commit-{0}-{1}',
            steps.setup-python.outputs.python-version,
            hashFiles('.pre-commit-config.yaml')
            ) }}
      - name: Pre-commit
        run: |
          poetry run pre-commit install
          poetry run pre-commit run --all-files
      - name: Test with pytest
        run: |
          poetry run pytest -vvv
